const ACCESS_TOKEN_SECRET = "abcdefghijklmnopqrstuvwxyABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
const REFRESH_TOKEN_SECRET = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxy";


module.exports = {
    ACCESS_TOKEN_SECRET,
    REFRESH_TOKEN_SECRET
}